sudo: required

branches:
  only:
  - master

services:
  - docker

before_install:
  - mkdir -p output
  - ls
  - docker pull runmyprocess/gitbook

script:
  - docker run -v $TRAVIS_BUILD_DIR:/documents --name md-to-html runmyprocess/gitbook gitbook serve /documents/docs/user_doc /documents/output

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: output
  on:
branch: master
