sudo: required

branches:
  only:
  - master

services:
  - docker

before_install:
  - mkdir -p gitbook
  - docker pull rianol/gitbook

script:
  - docker run --rm -v "$TRAVIS_BUILD_DIR:/gitbook" [-p 4000:4000] rianol/gitbook serve ./docs/user_doc ./gitbook
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: gitbook
  on:
branch: master
